### ISSUE TITLE
Failed to load plugin 'vuetify' declared in '.eslintrc.json': vue.camelize is not a function

### ISSUE THREAD

**Issue by dbssman** [vuetifyjs/eslint-plugin-vuetify#105]
This issue happens to me while trying to use the eslint plugin in a nuxt-bridge setup with vuetify 2.

**package.json**
```json
"eslint": "^8.56.0",
"eslint-config-prettier": "^8.10.0",
"eslint-plugin-vue": "^9.20.1",
"eslint-plugin-vuetify": "^2.4.0",
```

**eslint config**
```json
{
//...
"extends": [
	"eslint:recommended",
	"plugin:@typescript-eslint/recommended",
	"@nuxt/eslint-config",
	"plugin:vue/base",
	"plugin:vuetify/base",
	"prettier"
]
//...
}
```

**error log**
```
ESLint: 8.56.0

TypeError: Failed to load plugin 'vuetify' declared in '.eslintrc.json': vue.camelize is not a function
Referenced from: /Users/dennis-bosmans/source/etg24/main/packages/frontend/.eslintrc.json
    at ExpandTransitionGenerator (/Users/dennis-bosmans/source/etg24/main/packages/frontend/node_modules/vuetify/dist/vuetify.js:3194:32)
    at /Users/dennis-bosmans/source/etg24/main/packages/frontend/node_modules/vuetify/dist/vuetify.js:3409:77
    at /Users/dennis-bosmans/source/etg24/main/packages/frontend/node_modules/vuetify/dist/vuetify.js:8:66
    at Object.<anonymous> (/Users/dennis-bosmans/source/etg24/main/packages/frontend/node_modules/vuetify/dist/vuetify.js:11:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
```

**Comment by KaelWD** [comment]
Vuetify 3 will only work with Vue 3, there isn't much point trying to use this plugin with Vue 2.

**Comment by dbssman** [comment]
> Vuetify 3 will only work with Vue 3, there isn't much point trying to use this plugin with Vue 2.

So, as part of a migration you're saying that first we should be running vue3 and then installing the plugin to execute all the proper vuetify2 to vuetify3 changes?
