### ISSUE TITLE
ESLint 9: defineTemplateBodyVisitor is not a function

### ISSUE THREAD

**Issue by simon-kolkmann** [vuetifyjs/eslint-plugin-vuetify#108]
I'm just checking out the newly added ESLint 9 support, but the plugin throws an error:

```text
> eslint .

Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule 'vuetify/no-deprecated-classes': context.sourceCode.parserServices.defineTemplateBodyVisitor is not a function
Occurred while linting /path/to/project/.prettierrc.js
    at Object.create (/path/to/project/node_modules/eslint-plugin-vuetify/lib/rules/no-deprecated-classes.js:33:46)
    at createRuleListeners (/path/to/project/node_modules/eslint/lib/linter/linter.js:944:21)
    at /path/to/project/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/path/to/project/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/path/to/project/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/path/to/project/node_modules/eslint/lib/linter/linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (/path/to/project/node_modules/eslint/lib/linter/linter.js:2082:21)
    at Linter.verify (/path/to/project/node_modules/eslint/lib/linter/linter.js:1543:61)
    at Linter.verifyAndFix (/path/to/project/node_modules/eslint/lib/linter/linter.js:2320:29)
```

- ESLint: `9.15.0`
- eslint-plugin-vue: `9.31.0`
- eslint-plugin-vuetify: `2.5.0`

My ESLint configuration is copied from the docs:

```js
import vue from 'eslint-plugin-vue'
import vuetify from 'eslint-plugin-vuetify'

export default [...vue.configs['flat/base'], ...vuetify.configs['flat/base']]
```

The `.prettierrc.js` file in question looks like this:

```js
export { default } from '@my-org/prettier-config'
```

**Comment by simon-kolkmann** [comment]
@KaelWD Thanks for the quick fix! 💯
