### ISSUE TITLE
ERROR  TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by keeganwitt** [vuetifyjs/eslint-plugin-vuetify#7]
This happened in only 1 of the files in my project, but I'm not really sure what makes that component special.  The line it's failing on is basically `import MyOtherComponent from @/components/common/MyOtherComponent`.  The only Vuetify rule I'm running is the "no-deprecated-classes" rule.

eslint: 4.19.1
eslint-plugin-vue: 4.7.1
eslint-plugin-vuetify: 1.0.0-beta.3

I tried upgrading these versions (and some others), but that didn't seem to help.

```
 ERROR  TypeError: Cannot read property 'value' of null
Occurred while linting /Users/keegan/my-vuetify-project/src/components/widgets/MyComponent.vue:80
TypeError: Cannot read property 'value' of null
Occurred while linting /Users/keegan/my-vuetify-project/src/components/widgets/MyComponent.vue:80
    at EventEmitter.VAttribute[key.name="class"] (/Users/keegan/my-vuetify-project/node_modules/eslint-plugin-vuetify/lib/rules/no-deprecated-classes.js:112:36)
    at EventEmitter.emit (events.js:198:13)
    at NodeEventGenerator.applySelector (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:3128:26)
    at NodeEventGenerator.applySelectors (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:3142:22)
    at NodeEventGenerator.enterNode (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:3150:14)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:110:13)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:122:13)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:117:21)
    at traverseNodes (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:128:5)
    at scriptVisitor.Program:exit (/Users/keegan/my-vuetify-project/node_modules/vue-eslint-parser/index.js:3586:25)
error Command failed with exit code 1.
```

**Comment by jacekkarczmarczyk** [comment]
Check if you don't have an empty class (for example `<something class>`)

**Comment by keeganwitt** [comment]
Yep, it looks like that was the problem.  We can merge this into #2.
